apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server
spec:
  rules:
  - host: guestbook.glodon.com
    http:
      paths:
      - backend:
          serviceName: guestbook-ui
          servicePort: 80
        path: /
